In [41]:
import numpy as np

In [42]:
file = open('encrypted.txt', 'r')
string = file.read()
string = string.split()
string

['1',
 '45',
 '73080',
 '71055',
 '69750',
 '67860',
 '65340',
 '64800',
 '62595',
 '59805',
 '56970',
 '56430',
 '54810',
 '54000',
 '51480',
 '49545',
 '47340',
 '44505',
 '41670',
 '40230',
 '38475',
 '36630',
 '36090',
 '36000',
 '33390',
 '32760',
 '30510',
 '29610',
 '27630',
 '26145',
 '25875',
 '23130',
 '22140',
 '21600',
 '20745',
 '17910',
 '17235',
 '14940',
 '14940',
 '13500',
 '10845',
 '8145',
 '7110',
 '5265',
 '2565',
 '1215',
 '810',
 '130239',
 '128361',
 '124572',
 '121722',
 '118512',
 '114015',
 '111249',
 '106926',
 '101829',
 '98982',
 '97365',
 '92706',
 '90636',
 '88467',
 '83511',
 '79191',
 '76416',
 '72531',
 '69759',
 '68994',
 '65610',
 '63387',
 '61644',
 '58023',
 '56376',
 '55305',
 '51714',
 '50634',
 '45960',
 '41805',
 '40977',
 '39915',
 '36267',
 '32901',
 '31830',
 '29010',
 '24375',
 '21564',
 '19986',
 '17961',
 '14610',
 '13335',
 '9837',
 '5952',
 '2322',
 '152963',
 '150743',
 '147435',
 '142646',
 '138149',
 '135335',
 '131572',
 '126878',


In [43]:
dim = int(string[1])
D2 = np.zeros((dim, dim), dtype = int)
BA = np.zeros((dim, dim), dtype = int)

In [44]:
ptr = 2
for i in range(dim):
    for j in range(dim):
        BA[i, j] = int(string[ptr])
        ptr += 1

In [45]:
BA

array([[ 73080,  71055,  69750, ...,   2565,   1215,    810],
       [130239, 128361, 124572, ...,   9837,   5952,   2322],
       [152963, 150743, 147435, ...,   5914,   2894,    921],
       ...,
       [175090, 169420, 165570, ...,  16236,   9028,   4110],
       [172318, 169632, 166050, ...,  14600,  11102,   4122],
       [ 81032,  78792,  76048, ...,   8064,   4592,   3136]])

In [46]:
for i in range(dim):
    for j in range(dim):
        D2[i, j] = int(string[ptr])
        ptr += 1

In [47]:
D2

array([[10, 45, 12, ..., 35, 62, 32],
       [45, 29, 42, ..., 30,  9, 18],
       [34, 42, 55, ..., 55, 20, 21],
       ...,
       [ 9,  9, 10, ..., 23, 62, 43],
       [40, 49, 56, ..., 62, 26, 56],
       [38, 54, 38, ..., 37, 56, 26]])

In [48]:
# key matrix
A = np.zeros((dim, dim), dtype = int)
for i in range(dim):
    for j in range(i+1):
        A[i, j] = 1;
A

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1]])

In [49]:
D2_inv = np.linalg.inv(D2)
A_inv = np.linalg.inv(A)
B = np.dot(BA, A_inv)
D1 = np.dot(B, D2_inv)
D1

array([[ 4.34097203e-14,  4.50000000e+01, -6.05990952e-14, ...,
        -2.69836237e-15, -1.15185639e-15, -8.11434253e-14],
       [ 4.50000000e+01,  6.34735320e-15,  4.20000000e+01, ...,
         5.87004403e-14,  6.23112673e-15,  5.03624920e-14],
       [-1.97897254e-13,  4.20000000e+01,  9.10443596e-14, ...,
         9.08912702e-14, -7.31567584e-14,  1.11001486e-13],
       ...,
       [-2.34257058e-14, -3.26873945e-14, -2.73791406e-14, ...,
        -3.52053456e-14,  6.20000000e+01,  6.26582120e-14],
       [ 5.21804822e-15, -3.48211043e-14, -4.88168533e-14, ...,
         6.20000000e+01,  3.24879013e-14,  5.60000000e+01],
       [ 0.00000000e+00,  0.00000000e+00, -3.90798505e-14, ...,
        -2.84217094e-14,  5.60000000e+01, -2.97539771e-14]])

In [50]:
def inttochar(x):
    if(x >= 0 and x <= 9):
        return str(x)
    elif(x >= 10 and x <= 35):
        return chr(int(x + ord('A') - 10))
    elif(x == 36):
        return '.'
    elif(x == 37):
        return ' '
    elif(x >= 38 and x <= 63):
        return chr(int(x + ord('a') - 38))

In [54]:
decoded_message = ''
for i in range(dim - 1):
    decoded_message += inttochar(round(D1[i, i + 1]))
decoded_message

'here is an encryption algorithm for you guys'