In [4]:
import numpy as np

In [5]:
def chartoint(c):
    if(c >= '0' and c <= '9'):
        return int(c) - int('0')
    elif(c == '.'):
        return 36
    elif(c == ' '):
        return 37
    elif(c >= 'a' and c <= 'z'):
        return ord(c) - ord('a') + 38
    else:
        return ord(c) - ord('A') + 10

In [6]:
def encode(s):
    return [chartoint(char) for char in s]

In [71]:
# input string
s = 'hello world!'
s = encode(s)
print(s)

[45, 42, 49, 49, 52, 37, 60, 52, 55, 49, 41, -22]


In [72]:
# dimension of the adjacency matrix (dim, dim)
dim = len(s) + 1
D1 = np.zeros((dim, dim), dtype = int)

In [73]:
for i in range(dim-1):
    D1[i, i+1] = D1[i+1, i] = s[i]
D1

array([[  0,  45,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 45,   0,  42,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  42,   0,  49,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,  49,   0,  49,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  49,   0,  52,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,  52,   0,  37,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,  37,   0,  60,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,  60,   0,  52,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  52,   0,  55,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  55,   0,  49,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  49,   0,  41,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  41,   0, -22],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, -22,   0]])

In [74]:
D2 = np.random.randint(0, 64, (dim, dim))
D2

array([[40, 31, 28, 35, 25, 27,  2,  4, 53, 12, 51, 23, 42],
       [53, 22, 33,  3,  4, 36, 48, 13, 43, 20,  8, 29,  7],
       [14, 43, 19, 16,  5, 56, 20, 20, 60, 50, 32, 13, 53],
       [52, 12, 25, 60, 47, 14, 53, 16, 36,  4, 27, 60,  8],
       [52, 30, 15,  6, 47, 23, 20, 21, 53, 58, 55, 46, 50],
       [ 8, 40,  8, 45, 21, 48, 56, 20,  3,  0, 36,  9, 36],
       [46, 27, 25, 49, 31, 19, 26, 27, 52, 24, 31, 36, 28],
       [39, 16, 54,  9, 58, 11,  8, 28, 49, 15, 48, 25, 22],
       [27, 34, 43, 45, 35, 40,  8, 55, 55, 21, 54, 24, 61],
       [ 2, 34, 24, 48, 24, 26, 52, 47, 46, 13, 36, 57, 41],
       [59, 26, 61, 46, 59, 38, 56, 58, 56, 44,  1, 34, 27],
       [33, 13, 22, 25,  7, 23,  5, 43, 46, 16, 28, 40, 22],
       [ 4, 53, 60, 10, 44, 23, 37, 23, 36, 10, 14, 35, 50]])

In [75]:
for i in range(dim-1):
    D2[i, i+1] = D2[i+1, i] = s[i]
D2

array([[ 40,  45,  28,  35,  25,  27,   2,   4,  53,  12,  51,  23,  42],
       [ 45,  22,  42,   3,   4,  36,  48,  13,  43,  20,   8,  29,   7],
       [ 14,  42,  19,  49,   5,  56,  20,  20,  60,  50,  32,  13,  53],
       [ 52,  12,  49,  60,  49,  14,  53,  16,  36,   4,  27,  60,   8],
       [ 52,  30,  15,  49,  47,  52,  20,  21,  53,  58,  55,  46,  50],
       [  8,  40,   8,  45,  52,  48,  37,  20,   3,   0,  36,   9,  36],
       [ 46,  27,  25,  49,  31,  37,  26,  60,  52,  24,  31,  36,  28],
       [ 39,  16,  54,   9,  58,  11,  60,  28,  52,  15,  48,  25,  22],
       [ 27,  34,  43,  45,  35,  40,   8,  52,  55,  55,  54,  24,  61],
       [  2,  34,  24,  48,  24,  26,  52,  47,  55,  13,  49,  57,  41],
       [ 59,  26,  61,  46,  59,  38,  56,  58,  56,  49,   1,  41,  27],
       [ 33,  13,  22,  25,   7,  23,   5,  43,  46,  16,  41,  40, -22],
       [  4,  53,  60,  10,  44,  23,  37,  23,  36,  10,  14, -22,  50]])

In [76]:
B = np.dot(D1, D2)
B

array([[ 2025,   990,  1890,   135,   180,  1620,  2160,   585,  1935,
          900,   360,  1305,   315],
       [ 2388,  3789,  2058,  3633,  1335,  3567,   930,  1020,  4905,
         2640,  3639,  1581,  4116],
       [ 4438,  1512,  4165,  3066,  2569,  2198,  4613,  1330,  3570,
         1036,  1659,  4158,   686],
       [ 3234,  3528,  1666,  4802,  2548,  5292,  1960,  2009,  5537,
         5292,  4263,  2891,  5047],
       [ 2964,  2668,  2817,  5280,  5105,  3182,  4521,  1824,  1920,
          196,  3195,  3408,  2264],
       [ 4406,  2559,  1705,  4361,  3591,  4073,  2002,  3312,  4680,
         3904,  4007,  3724,  3636],
       [ 2636,  2440,  3536,  2205,  5404,  2436,  4969,  2420,  3231,
          900,  4212,  1833,  2652],
       [ 4164,  3388,  3736,  5280,  3680,  4300,  1976,  6304,  5980,
         4300,  4668,  3408,  4852],
       [ 2138,  2702,  4128,  3108,  4336,  2002,  5980,  4041,  5729,
         1495,  5191,  4435,  3399],
       [ 4376,  3144,  5354,

In [77]:
# key matrix
A = np.zeros((dim, dim), dtype = int)
for i in range(dim):
    for j in range(i+1):
        A[i, j] = 1;
A

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [78]:
BA = np.dot(B, A)
BA

array([[14400, 12375, 11385,  9495,  9360,  9180,  7560,  5400,  4815,
         2880,  1980,  1620,   315],
       [35601, 33213, 29424, 27366, 23733, 22398, 18831, 17901, 16881,
        11976,  9336,  5697,  4116],
       [35000, 30562, 29050, 24885, 21819, 19250, 17052, 12439, 11109,
         7539,  6503,  4844,   686],
       [48069, 44835, 41307, 39641, 34839, 32291, 26999, 25039, 23030,
        17493, 12201,  7938,  5047],
       [39344, 36380, 33712, 30895, 25615, 20510, 17328, 12807, 10983,
         9063,  8867,  5672,  2264],
       [45960, 41554, 38995, 37290, 32929, 29338, 25265, 23263, 19951,
        15271, 11367,  7360,  3636],
       [38874, 36238, 33798, 30262, 28057, 22653, 20217, 15248, 12828,
         9597,  8697,  4485,  2652],
       [56036, 51872, 48484, 44748, 39468, 35788, 31488, 29512, 23208,
        17228, 12928,  8260,  4852],
       [48684, 46546, 43844, 39716, 36608, 32272, 30270, 24290, 20249,
        14520, 13025,  7834,  3399],
       [57588, 53212, 50068,

In [96]:
file_to_be_sent = open('encrypted.txt', 'w')

In [97]:
string = str(1) + ' ' + str(dim) + ' '
for i in range(dim):
    for j in range(dim):
        string += str(BA[i, j]) + ' '
string

'1 13 14400 12375 11385 9495 9360 9180 7560 5400 4815 2880 1980 1620 315 35601 33213 29424 27366 23733 22398 18831 17901 16881 11976 9336 5697 4116 35000 30562 29050 24885 21819 19250 17052 12439 11109 7539 6503 4844 686 48069 44835 41307 39641 34839 32291 26999 25039 23030 17493 12201 7938 5047 39344 36380 33712 30895 25615 20510 17328 12807 10983 9063 8867 5672 2264 45960 41554 38995 37290 32929 29338 25265 23263 19951 15271 11367 7360 3636 38874 36238 33798 30262 28057 22653 20217 15248 12828 9597 8697 4485 2652 56036 51872 48484 44748 39468 35788 31488 29512 23208 17228 12928 8260 4852 48684 46546 43844 39716 36608 32272 30270 24290 20249 14520 13025 7834 3399 57588 53212 50068 44714 39985 35169 31107 27923 22221 16452 11026 8007 4678 35100 33649 31450 29372 25995 24532 22315 19562 15496 10915 9622 5540 1107 16133 13802 13902 12721 11055 9604 8552 7070 5198 3694 1905 2172 7 -6424 -5698 -5412 -4928 -4378 -4224 -3718 -3608 -2662 -1650 -1298 -396 484 '

In [98]:
for i in range(dim):
    for j in range(dim):
        string += str(D2[i, j]) + ' '
string

'1 13 14400 12375 11385 9495 9360 9180 7560 5400 4815 2880 1980 1620 315 35601 33213 29424 27366 23733 22398 18831 17901 16881 11976 9336 5697 4116 35000 30562 29050 24885 21819 19250 17052 12439 11109 7539 6503 4844 686 48069 44835 41307 39641 34839 32291 26999 25039 23030 17493 12201 7938 5047 39344 36380 33712 30895 25615 20510 17328 12807 10983 9063 8867 5672 2264 45960 41554 38995 37290 32929 29338 25265 23263 19951 15271 11367 7360 3636 38874 36238 33798 30262 28057 22653 20217 15248 12828 9597 8697 4485 2652 56036 51872 48484 44748 39468 35788 31488 29512 23208 17228 12928 8260 4852 48684 46546 43844 39716 36608 32272 30270 24290 20249 14520 13025 7834 3399 57588 53212 50068 44714 39985 35169 31107 27923 22221 16452 11026 8007 4678 35100 33649 31450 29372 25995 24532 22315 19562 15496 10915 9622 5540 1107 16133 13802 13902 12721 11055 9604 8552 7070 5198 3694 1905 2172 7 -6424 -5698 -5412 -4928 -4378 -4224 -3718 -3608 -2662 -1650 -1298 -396 484 40 45 28 35 25 27 2 4 53 12 51 23 

In [99]:
file_to_be_sent.write(string)
file_to_be_sent.close()